site_name: Dissecting Offensive Security
site_description: A blog by Hugo Picanzo
site_url: https://todo.com
theme: 
  name: material
  language: en
  font:
    text: Roboto
    code: Inconsolata
 # logo: path/to/file.png #to change
  favicon: path/to/file.png #to change
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red

      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
        #TODO: define in the future
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# footer, to decide

extra:
  generator: false

  # to change
  
  #analytics:
  #  provider: google
  #  property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
  #  - icon: fontawesome/brands/bluesky
  #    link: https://bsky.app/profile/squidfunk.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk
  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright © 2025 Hugo Picanço

plugins:

# TODO: decide if I want to implement tags  
#  - tags:
#      tags_file: tags.md
  - blog
  - search

#TODO: to change

repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material


# Page tree



